/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function O(a){"@babel/helpers - typeof";return O="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"==typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c},O(a)}function G(){console.error.apply(console,arguments)}function fd(){console.warn.apply(console,arguments)}function gd(){if(fc)return Za.exports;fc=1;(function(a,c){(function(e,g){a.exports=g()})(hd,function(){function e(r){return r.charAt(0).toUpperCase()+
r.substring(1)}function g(r){return function(){return this[r]}}function h(r){if(r)for(var t=0;t<v.length;t++)if(void 0!==r[v[t]])this["set"+e(v[t])](r[v[t]])}var p=["isConstructor","isEval","isNative","isToplevel"],n=["columnNumber","lineNumber"],q=["fileName","functionName","source"],v=p.concat(n,q,["args"],["evalOrigin"]);h.prototype={getArgs:function(){return this.args},setArgs:function(r){if("[object Array]"!==Object.prototype.toString.call(r))throw new TypeError("Args must be an Array");this.args=
r},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(r){if(r instanceof h)this.evalOrigin=r;else if(r instanceof Object)this.evalOrigin=new h(r);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var r=this.getFileName()||"",t=this.getLineNumber()||"",F=this.getColumnNumber()||"",K=this.getFunctionName()||"";return this.getIsEval()?r?"[eval] ("+r+":"+t+":"+F+")":"[eval]:"+t+":"+F:K?K+" ("+r+":"+t+":"+F+")":r+":"+t+":"+F}};h.fromString=
function(r){var t=r.indexOf("("),F=r.lastIndexOf(")"),K=r.substring(0,t);t=r.substring(t+1,F).split(",");r=r.substring(F+1);if(0===r.indexOf("@")){var J=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(r,""),T=J[1],H=J[2];J=J[3]}return new h({functionName:K,args:t||void 0,fileName:T,lineNumber:H||void 0,columnNumber:J||void 0})};for(var w=0;w<p.length;w++)h.prototype["get"+e(p[w])]=g(p[w]),h.prototype["set"+e(p[w])]=function(r){return function(t){this[r]=!!t}}(p[w]);for(p=0;p<n.length;p++)h.prototype["get"+e(n[p])]=
g(n[p]),h.prototype["set"+e(n[p])]=function(r){return function(t){if(isNaN(parseFloat(t))||!isFinite(t))throw new TypeError(r+" must be a Number");this[r]=Number(t)}}(n[p]);for(n=0;n<q.length;n++)h.prototype["get"+e(q[n])]=g(q[n]),h.prototype["set"+e(q[n])]=function(r){return function(t){this[r]=String(t)}}(q[n]);return h})})(Za);return Za.exports}function La(a){var c=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return c?c[1]:a}function gc(a){var c=document.createElement("a");c.href=a;return{href:c.href,
hostname:c.hostname,pathname:c.pathname}}function hc(a,c){if(-1===a.indexOf("?"+c+"=")&&-1===a.indexOf("&"+c+"="))return a;var e=a.indexOf("?");if(-1===e)return a;var g=a.substr(e+1);e=a.substr(0,e);if(g){var h="",p=g.indexOf("#");-1!==p&&(h=g.substr(p+1),g=g.substr(0,p));p=g.split("&");for(var n=p.length-1;0<=n;n--)g=p[n].split("=")[0],g===c&&p.splice(n,1);(g=p.join("&"))&&(e=e+"?"+g);h&&(e+="#"+h)}return e}function ic(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function tb(a,c){a=a.toLowerCase();
c=c.toLowerCase();if(a===c)return!0;if("."===c.slice(0,1)){if(a===c.slice(1))return!0;var e=a.length-c.length;if(0<e&&a.slice(e)===c)return!0}return!1}function $a(a,c){var e=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(0===a.indexOf("*")&&(a=a.substr(1)),0===a.indexOf(".")&&(a=a.substr(1)),a="http://"+a);e.href=c.toAbsoluteUrl(a);return e.pathname?e.pathname:""}function ab(a,c){return c&&a?0===a.indexOf(c):!1}function ub(a,c){var e=(new RegExp("[\\?&#]"+c+"=([^&#]*)")).exec(a);
return e?decodeURIComponent(e[1]):""}function bb(a,c){a=hc(a,c.visitorIdUrlParameter);return c.discardHashTag?a.replace(/#.*/,""):a}function x(a){return"undefined"!==typeof a}function va(a){return"function"===typeof a}function Ma(a){return"object"===O(a)}function P(a){return"string"===typeof a||a instanceof String}function pa(a){return"number"===typeof a||P(a)&&!isNaN(a)&&""!==a}function Na(a){var c=a.length;"."===a.charAt(--c)&&(a=a.slice(0,c));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&
(a=a.substr(0,a.indexOf("/")));return a}function id(a,c,e){a||(a="");c||(c="");if("translate.googleusercontent.com"===a)""===e&&(e=c),c=ub(c,"u"),a=La(c);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))c=document.links[0].href,a=La(c);return[a,c,e]}function Y(a,c){if(a&&a.indexOf)return a.indexOf(c);if(!x(a)||null===a||0===a.length)return-1;for(var e=0;e<a.length;){if(a[e]===c)return e;e++}return-1}function jc(a){if(a)return!x(a.children)&&x(a.childNodes)||
x(a.children)?a.children:[]}function vb(a){var c;for(c=a.parentNode;null!==c&&x(c)&&!u.isLinkElement(a);)a=c,c=a.parentNode;return a}function wb(a){return Math.round((a||new Date).getTime()/1E3)}function wa(a,c){return-1!==a.indexOf(c,a.length-c.length)}function xb(a,c){var e="(^| )(piwik[_-]"+c;if(a)for(var g=0;g<a.length;g++)e+="|"+a[g];return new RegExp(e+")( |$)")}function jd(a,c){var e=u.getAttributeValueFromNode(a,"href");if(!e)return!1;var g=e.split("://");if(2!==g.length)return!1;e=g[0].toLowerCase();
g=g[1];var h=g.indexOf("?");g=-1===h?g:g.slice(0,h);h=[];for(var p=0;p<c.length;p++){var n=c[p];kd.test(n)&&h.push(n)}for(p=0;p<h.length;p++){var q=h[p].split("://");if(2!==q.length)break;n=q[0].toLowerCase();q=q[1];if(e===n&&kc(g,q))return!0}return!1}function kc(a,c){0!==c.lastIndexOf("/",0)&&(c="/"+c);0!==a.lastIndexOf("/",0)&&(a="/"+a);if("/"===c||"/*"===c||a===c)return!0;c=c.toLowerCase();a=a.toLowerCase();if(wa(c,"*"))return(c=c.slice(0,-1))&&"/"!==c&&a!==c?0===a.indexOf(c):!0;wa(a,"/")||(a+=
"/");wa(c,"/")||(c+="/");return 0===a.indexOf(c)}function lc(a,c,e,g){for(var h=0;h<e.length;h++){var p=Na(e[h]),n=$a(e[h],g);if(tb(a,p)&&kc(c,n))return!0}return!1}function mc(a,c,e){a=vb(a);if(u.hasNodeAttribute(a,"href")){var g=u.getAttributeValueFromNode(a,"href");if(g&&!ab(g,e.configTrackerUrl)){var h=gc(g),p=h.pathname||$a(g,c);g=h.hostname||La(h.href);var n=g.toLowerCase();h=h.href.replace(g,n);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(h)&&
(g=a.className,c=lc(n,p,e.configHostsAlias,c),a=u.hasNodeAttribute(a,"download"),ab(h,e.configTrackerUrl)?e=0:(p=xb(e.configDownloadClasses,"download"),n=xb(e.configLinkClasses,"link"),e=new RegExp("\\.("+e.configDownloadExtensions.join("|")+")([?&#]|$)","i"),e=n.test(g)?"link":a||p.test(g)||e.test(h)?"download":c?0:"link"),e))return{type:e,href:h}}}}function Q(a,c,e){return 0<=c&&c<=e?"&"+a+"="+c.toString():""}function R(a,c){var e=a[c];return"number"!==typeof e?0:Math.round(e-(a.navigationStart||
0))}function ld(a){var c,e={state:"loading"};if(null!==(c=navigator.userAgentData)&&void 0!==c&&c.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues(md).then(function(g){e={state:"available",hints:g};a.onResolve()})["catch"](function(){e={state:"unavailable"};a.onResolve()});else e={state:"unavailable"};return{getState:function(){return e}}}function nc(a){if(!(a instanceof Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(JSON.stringify(a),
"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var c=0;c<a.length;c++)if("number"!==typeof a[c])return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(JSON.stringify(a),"'")};return{isValid:!0}}function nd(a){var c=!1,e=!1,g=!0,h=oc,p,n=0,q=function(){var r=h[n];p=void 0===r?void 0:window.setTimeout(function(){if(g)a.onPing(qa.PeriodicHeartbeat);n++;q()},1E3*r)},v=function(){e&&
(q(),e=!1);g||(g=!0,a.onPing(qa.PeriodicHeartbeat))},w=function(){g=!1;a.onPing(qa.BlurHeartbeat)};return{enable:function(){c=!0;window.addEventListener("focus",v);window.addEventListener("blur",w);document.hasFocus()?q():e=!0},disable:function(){e=c=!1;clearTimeout(p);p=void 0;n=0;window.removeEventListener("focus",v);window.removeEventListener("blur",w)},setTimings:function(r){var t=nc(r);t.isValid||G(t.error);h=r},isEnabled:function(){return c}}}function od(){var a=[[/g/g,"10"],[/h/g,"11"],[/i/g,
"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]],c=/^[0-9a-f]{16}$/;return function(e){if(e&&!c.test(e)){e=e.toLowerCase().substr(4,16);for(var g=0;g<a.length;g+=1)e=e.replace(a[g][0],a[g][1]);e=e.substr(0,16)}return e}}function pd(a){return{transformIfAMPCookie:od(),getCookieName:function(c){var e=a.getCookiesConfig();
return e.cookieNamePrefix+c+"."+String(e.trackerSiteId)+"."+e.domainHash},getCookie:function(c){return a.getCookiesConfig().cookiesDisabled?0:(c=(new RegExp("(^|;)[ ]*"+c+"=([^;]*)")).exec(a.documentAlias.cookie))?a.decodeWrapper(c[2])||0:0},setCookie:function(c,e,g){var h=a.getCookiesConfig();h.msToExpire=g?g.msToExpire||h.msToExpire:h.msToExpire;h.path=g?g.path||h.path:h.path;h.cookiesDisabled||(e=a.encodeWrapper(e),g=h.msToExpire?new Date(Date.now()+h.msToExpire):void 0,c=c+"="+e+(g?";expires="+
g.toUTCString():"")+";path="+(h.path||"/")+(h.domain?";domain="+h.domain:"")+(h.isSecure?";secure":"")+";SameSite=Lax",document.cookie=c)},deleteCookie:function(c){this.setCookie(c,"",{msToExpire:-86400})},hasCookies:function(){if(a.getCookiesConfig().cookiesDisabled)return"0";if(!x(a.navigatorAlias.cookieEnabled)){var c=this.getCookieName("_pk_testcookie");this.setCookie(c,"1");var e="1"===this.getCookie(c)?"1":"0";this.deleteCookie(c);return e}return a.navigatorAlias.cookieEnabled?"1":"0"}}}function yb(a){function c(g,
h){if(window.getComputedStyle)return document.defaultView.getComputedStyle(g,null)[h];if(g.currentStyle)return g.currentStyle[h]}function e(g,h,p,n,q,v,w){var r=g.parentNode,t;a:{for(t=g.parentNode;t;){if(t===document){t=!0;break a}t=t.parentNode}t=!1}if(!t)return!1;if(9===r.nodeType)return!0;if("0"===c(g,"opacity")||"none"===c(g,"display")||"hidden"===c(g,"visibility"))return!1;x(h)&&x(p)&&x(n)&&x(q)&&x(v)&&x(w)||(h=g.offsetTop,q=g.offsetLeft,n=h+g.offsetHeight,p=q+g.offsetWidth,v=g.offsetWidth,
w=g.offsetHeight);if(a===g&&(0===w||0===v)&&"hidden"===c(g,"overflow"))return!1;if(r){if("hidden"===c(r,"overflow")||"scroll"===c(r,"overflow"))if(q+1>r.offsetWidth+r.scrollLeft||q+v-1<r.scrollLeft||h+1>r.offsetHeight+r.scrollTop||h+w-1<r.scrollTop)return!1;g.offsetParent===r&&(q+=r.offsetLeft,h+=r.offsetTop);return e(r,h,p,n,q,v,w)}return!0}return a?e(a):!1}function pc(a){var c=function(xa,Z){return xa<<Z|xa>>>32-Z},e=function(xa){var Z="",ca;for(ca=7;0<=ca;ca--){var zb=xa>>>4*ca&15;Z+=zb.toString(16)}return Z},
g,h=[],p=1732584193,n=4023233417,q=2562383102,v=271733878,w=3285377520,r=[];a=unescape(encodeURIComponent(a));var t=a.length;for(g=0;g<t-3;g+=4){var F=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);r.push(F)}switch(t&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(t-1)<<24|8388608;break;case 2:g=a.charCodeAt(t-2)<<24|a.charCodeAt(t-1)<<16|32768;break;case 3:g=a.charCodeAt(t-3)<<24|a.charCodeAt(t-2)<<16|a.charCodeAt(t-1)<<8|128}for(r.push(g);14!==(r.length&15);)r.push(0);
r.push(t>>>29);r.push(t<<3&4294967295);for(a=0;a<r.length;a+=16){for(g=0;16>g;g++)h[g]=r[a+g];for(g=16;79>=g;g++)h[g]=c(h[g-3]^h[g-8]^h[g-14]^h[g-16],1);F=p;t=n;var K=q;var J=v;var T=w;for(g=0;19>=g;g++){var H=c(F,5)+(t&K|~t&J)+T+h[g]+1518500249&4294967295;T=J;J=K;K=c(t,30);t=F;F=H}for(g=20;39>=g;g++)H=c(F,5)+(t^K^J)+T+h[g]+1859775393&4294967295,T=J,J=K,K=c(t,30),t=F,F=H;for(g=40;59>=g;g++)H=c(F,5)+(t&K|t&J|K&J)+T+h[g]+2400959708&4294967295,T=J,J=K,K=c(t,30),t=F,F=H;for(g=60;79>=g;g++)H=c(F,5)+(t^
K^J)+T+h[g]+3395469782&4294967295,T=J,J=K,K=c(t,30),t=F,F=H;p=p+F&4294967295;n=n+t&4294967295;q=q+K&4294967295;v=v+J&4294967295;w=w+T&4294967295}H=e(p)+e(n)+e(q)+e(v)+e(w);return H.toLowerCase()}function ya(a,c){if("undefined"===typeof a)return!0;if("object"!==O(a)||null===a)return G("[".concat(c,"]: parameter 'options' have to be of type object or undefined. Received: ").concat(JSON.stringify(a))),!1;if("string"===typeof a.currencyCode||"undefined"===typeof a.currencyCode)return!0;G("[".concat(c,
"]: parameter 'options.currencyCode' has to be of type string or undefined Received: ").concat(JSON.stringify(a.currencyCode)));return!1}function W(a,c,e,g){if(a.addEventListener)return a.addEventListener(c,e,g),!0;if(a.attachEvent)return a.attachEvent("on"+c,e);a["on"+c]=e}function qd(a){var c={};if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(var e in Ab)if(Object.prototype.hasOwnProperty.call(Ab,e)){var g=navigator.mimeTypes[Ab[e]];c[e]=g&&g.enabledPlugin?
"1":"0"}va(navigator.javaEnabled)&&navigator.javaEnabled()&&(c.java="1");va(window.GearsFactory)&&(c.gears="1");c.cookie=a()}a=parseInt(screen.width,10);e=parseInt(screen.height,10);c.res=a.toString()+"x"+e.toString();return c}function qc(a,c){c||(c=pc);return c((navigator.userAgent||"")+(navigator.platform||"")+JSON.stringify(a)).slice(0,6)}function rc(a){var c=Math.floor((new Date).getTime()/1E3);a=qc(a);return String(c)+a}function rd(a,c,e,g){if(!e.crossDomainTrackingEnabled)return"";g||(g=ub);
a=g(a,e.configVisitorIdUrlParameter);if(!a)return"";a=String(a);g=/^[a-zA-Z0-9]+$/;if(16===a.length&&g.test(a))return a;if(32===a.length&&g.test(a)){a:{g=a.substr(16,32);e=e.configVisitorIdUrlParameterTimeoutInSeconds;c=qc(c);var h=c.length,p=g.substr(-1*h,h);if((g=parseInt(g.substr(0,g.length-h),10))&&p&&p===c){c=Math.floor((new Date).getTime()/1E3);if(0>=e){e=!0;break a}if(c>=g&&c<=g+e){e=!0;break a}}e=!1}if(e)return a.substr(0,16)}return""}function sc(a,c,e){if(a&&u.hasNodeAttribute(a,"href")){var g=
u.getAttributeValueFromNode(a,"href");g&&!ab(g,e.configTrackerUrl)&&(g=(e.crossDomainTrackingLinkDecorator||tc)(g,c+rc(e.browserFeatures),e.configVisitorIdUrlParameter),null!==g&&u.setAnyAttribute(a,"href",g))}}function tc(a,c,e){a=hc(a,e);c||(c="");var g=document.createElement("a");g.href=a;a=g.search.split("&");a.push(encodeURIComponent(e)+"="+encodeURIComponent(c));""===a[0]&&a.shift();g.search=a.join("&");return g.href}function sd(a,c,e){for(var g=[],h=[],p=[],n=0;n<a.length;n++){var q=a[n];q&&
(-1<Y(c,q[0])?g.push(q):-1<Y(e,q[0])?p.push(q):h.push(q))}return{toApplyFirst:g,toApplySecond:h,toApplyLast:p}}function Bb(a){if(!a)return!0;var c,e=!0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(e=!1);return e}function za(){for(var a=0;a<arguments.length;a+=1){var c=arguments[a];if(!Array.isArray(c)){G("[".concat(I.queueName,".push()]: expected array as argument, got ").concat(JSON.stringify(c),". Example: ").concat(I.queueName,".push(['methodName', parameters]) or ").concat(I.queueName,
".push([function(){}])"));break}for(var e=c.shift(),g=0;g<U.length;g++){var h=U[g];if(va(e))e.apply(h,c);else if(P(e)){h[e]?h[e].apply(h,c):(h="The method '".concat(e,"' was not found in \"").concat(I.queueName,'" variable.  Please have a look at the Piwik tracker documentation'),G(h));if("addTracker"===e)break;if("setTrackerUrl"===e||"setSiteId"===e)break}}}}function cb(a,c,e,g){if(a.removeEventListener)return a.removeEventListener(c,e,g),!0;if(a.detachEvent)return a.detachEvent("on"+c,e);a["on"+
c]===e&&delete a["on"+c]}function Aa(a){"complete"===C.readyState?a():A.addEventListener?A.addEventListener("load",a):A.attachEvent&&A.attachEvent("onload",a)}function Oa(a){var c=!1;(c=C.attachEvent?"complete"===C.readyState:"loading"!==C.readyState)?a():(C.addEventListener?W(C,"DOMContentLoaded",function g(){C.removeEventListener("DOMContentLoaded",g,!1);c||(c=!0,a())}):C.attachEvent&&(C.attachEvent("onreadystatechange",function g(){"complete"===C.readyState&&(C.detachEvent("onreadystatechange",
g),c||(c=!0,a()))}),C.documentElement.doScroll&&A===A.top&&function h(){if(!c){try{C.documentElement.doScroll("left")}catch(p){setTimeout(h,0);return}c=!0;a()}}()),W(A,"load",function(){c||(c=!0,a())},!1))}function td(){var a="";try{var c;a=(null===(c=A.top)||void 0===c?void 0:c.document.referrer)||""}catch(e){if(A.parent)try{a=A.parent.document.referrer}catch(g){a=""}}""===a&&(a=C.referrer);return a}function da(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a}function uc(a,c){return a&&c?
a.contains?a.contains(c):a===c?!0:a.compareDocumentPosition?!!(a.compareDocumentPosition(c)&16):!1:!1}function Cb(a,c){function e(b){if(!1===Db||!0===Eb){var d=new Date;null!==Fb&&18E5<d.getTime()-Fb.getTime()||(d=H("ping=".concat(String(b)),null,"ping"),b=b!==qa.PeriodicHeartbeat,q(d,L,null,b,b?"beacon":void 0))}}function g(b,d){var f=new Image(1,1);f.onload=function(){va(d)&&d()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";f.src=aa+(0>aa.indexOf("?")?
"?":"&")+b}function h(b,d,f){x(f)||(f=!0);try{var k=A.XMLHttpRequest?new A.XMLHttpRequest:A.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;k.open("POST",aa,!0);k.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!f?4===this.readyState&&"function"===typeof d&&d():g(b,d)};k.setRequestHeader("Content-Type",Gb);k.send(b)}catch(l){f&&g(b,d)}}function p(b){b=(new Date).getTime()+b;if(!db||b>db)db=b}function n(b,d){var f=(new Date).getTime();vc=f;Ba&&f<Ba?(f=
Ba-f,setTimeout(b,f),d&&p(f+50),Ba+=50):(void 0===Ba&&(Ba=f+800),b())}function q(b,d,f,k,l){if(Hb){var z=wc.getState();if("loading"===z.state){eb.push({type:"single",request:b,delay:d,callback:f,force:k,method:l});return}"available"===z.state&&(b+=xc(z.hints))}va(Pa)&&(b=Pa(b)||"");if(!fb&&b){b=String(b);var y=l||gb,D=!f&&ra.sendBeacon&&A.Blob&&65536>=b.length,N=!0;l=function(){if("beacon"===y&&D){var ha=new A.Blob([b],{type:Gb});ra.sendBeacon(aa,ha)?N=!1:h(b,f)}else"POST"===y||2E3<b.length?h(b,f):
g(b,f);N&&p(d)};k?l():n(l,N)}}function v(b,d){var f=fb?!1:b?0<b.length:!1;if(f){if(Hb){f=wc.getState();if("loading"===f.state){eb.push({type:"bulk",requests:b,delay:d});return}if("available"===f.state)for(var k=0;k<b.length;k++)b[k]+=xc(f.hints)}if(va(Pa)){f=[];for(k=0;k<b.length;k++){var l=Pa(b[k]);l&&f.push(l)}if(0>=f.length)return;b=f}var z='{"requests":["?'+b.join('","?')+'"]}';n(function(){h(z,null,!1);"beacon"!==gb&&p(d)},!1)}}function w(){yc=zc((hb||Qa)+(ib||"/")).slice(0,4)}function r(){var b=
M.getCookieName("cvar");b=M.getCookie(b);return P(b)&&b.length&&(b=JSON.parse(b),Ma(b))?b:{}}function t(){Ca||(Ca=rd(jb,ia,{crossDomainTrackingEnabled:Da,configVisitorIdUrlParameter:"pk_vid",configVisitorIdUrlParameterTimeoutInSeconds:Ac},Bc));var b=wb(new Date),d=M.getCookieName("id");d=M.getCookie(d);return P(d)&&d.length?(d=d.split("."),d[0]=M.transformIfAMPCookie(d[0]),6>d.length&&(d[1]=b,d[2]=1,d[3]=b,d[4]="",d[5]=""),d.unshift("0"),Ca.length&&(d[1]=Ca),d):d=["1",Ca.length?Ca:"0"===M.hasCookies()?
"":zc((ra.userAgent||"")+(ra.platform||"")+JSON.stringify(ia)+(new Date).getTime()+Math.random()).slice(0,16),b,1,b,"",""]}function F(){var b=t(),d=b[0],f=b[1],k=b[2],l=b[3],z=b[4],y=b[5];x(b[6])||(b[6]="");return{newVisitor:d,uuid:f,createTs:k,visitCount:l,currentVisitTs:z,lastVisitTs:y,lastEcommerceOrderTs:b[6]}}function K(b){Ea&&(x(b)||(b=F()),b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+b.currentVisitTs+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs,M.setCookie(M.getCookieName("id"),b,{msToExpire:Ib}))}
function J(){var b=sa;sa=!1;var d;for(d=0;d<Jb.length;d++){var f=M.getCookieName(Jb[d]);0!==M.getCookie(f)&&M.deleteCookie(f)}sa=b}function T(b){var d=[];for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&d.push(f);var f={};d.sort();var k=d.length,l;for(l=0;l<k;l++)f[d[l]]=b[d[l]];return f}function H(b,d,f,k){var l=new Date;var z=wb(l);var y=S,D=M.getCookieName("ses"),N=M.getCookieName("cvar"),ha=M.getCookie(D),Sa=Ra||jb;sa&&J();if(fb)return"";D=F();x(k)||(k="");var ta=C.characterSet||C.charset;
ta&&"utf-8"!==ta.toLowerCase()||(ta=void 0);!ha&&z-Number(D.lastVisitTs||D.createTs)>Fa/1E3&&(D.visitCount=Number(D.visitCount)+1,D.lastVisitTs=D.currentVisitTs,D.currentVisitTs=z);0===b.lastIndexOf("action_name=",0)&&(Db=kb,Eb=!!D.uuid,Fb=new Date);b+="&idsite="+Ea+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+l.getHours()+"&m="+l.getMinutes()+"&s="+l.getSeconds()+"&url="+E(bb(Sa,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"}))+(Kb.length?"&urlref="+E(bb(Kb,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"})):
"")+(Ua.length?"&uid="+E(Ua):"")+(kb?"&uia=1":"")+(D.uuid?"&_id="+D.uuid:"")+"&_idts="+D.createTs+"&_idvc="+D.visitCount+(D.lastVisitTs?"&_viewts="+D.lastVisitTs:"")+(String(D.lastEcommerceOrderTs).length?"&_ects="+D.lastEcommerceOrderTs:"")+(ta?"&cs="+E(ta):"")+"&ts_n="+E(lb||Lb)+"&ts_v="+E(Mb||Nb)+(Cc?"":"&rmip=1")+(Dc&&kb?"&dda=1":"");if(!Ec)for(m in ia)Object.prototype.hasOwnProperty.call(ia,m)&&(b+="&"+m+"="+ia[m]);l=[];if(d)for(m in d)Object.prototype.hasOwnProperty.call(d,m)&&/^dimension\d+$/.test(m)&&
(z=m.replace("dimension",""),l.push(parseInt(z,10)),l.push(z),b+="&"+m+"="+d[m],delete d[m]);d&&Bb(d)&&(d=null);for(m in ea)Object.prototype.hasOwnProperty.call(ea,m)&&(z=-1===Y(l,m))&&(z=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==z.exec(ea[m])?b+("&dimension"+m+"="+encodeURIComponent(ea[m])):b+("&dimension"+m+"="+ea[m]));for(m in na)Object.prototype.hasOwnProperty.call(na,m)&&(z=-1===Y(l,m))&&(b+="&dimension"+encodeURIComponent(m)+
"="+encodeURIComponent(na[m]));d?b+="&data="+E(JSON.stringify(d)):oa&&(b+="&data="+E(JSON.stringify(oa)));Bb(ja)||(d=T(ja),b+="&cvar="+E(JSON.stringify(d)));Bb(Va)||(d=T(Va),b+="&e_cvar="+E(JSON.stringify(d)));if(S){b+="&_cvar="+E(JSON.stringify(S));for(m in y)Object.prototype.hasOwnProperty.call(y,m)&&(""===S[m][0]||""===S[m][1])&&delete S[m];Fc&&M.setCookie(N,JSON.stringify(S),{msToExpire:Fa})}var m=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;m=null!==
m&&void 0!==m&&m.timing?m.timing:null!==m&&void 0!==m&&m.getEntriesByType?m.getEntriesByType("navigation")[0]:void 0;y=null;Ob&&(Pb?y=Pb:m&&m.requestStart&&m.responseEnd&&(y=m.responseEnd-m.requestStart),null!==y&&(b+="&gt_ms="+Math.max(y,0)));y=m&&m.loadEventEnd&&0!==m.loadEventEnd&&m.fetchStart&&0!==m.fetchStart;Ob&&("log"===f||"ping"===f)&&2>=mb&&!Gc&&y&&(f="",m.unloadEventStart&&0!==m.unloadEventStart&&(f+=Q("t_us",R(m,"unloadEventStart"),65535)),m.unloadEventEnd&&0!==m.unloadEventEnd&&(f+=Q("t_ue",
R(m,"unloadEventEnd"),65535)),m.redirectStart&&0!==m.redirectStart&&(f+=Q("t_rs",R(m,"redirectStart"),65535)),m.redirectEnd&&0!==m.redirectEnd&&(f+=Q("t_re",R(m,"redirectEnd"),65535)),m.secureConnectionStart&&0!==m.secureConnectionStart&&(f+=Q("t_ss",R(m,"secureConnectionStart"),65535)),m.fetchStart&&0!==m.fetchStart&&(f+=Q("t_fs",R(m,"fetchStart"),65535)),m.domainLookupStart&&0!==m.domainLookupStart&&(f+=Q("t_ds",R(m,"domainLookupStart"),65535)),m.connectStart&&0!==m.connectStart&&(f+=Q("t_cs",R(m,
"connectStart"),65535)),m.connectEnd&&0!==m.connectEnd&&(f+=Q("t_ce",R(m,"connectEnd"),65535)),m.requestStart&&0!==m.requestStart&&(f+=Q("t_qs",R(m,"requestStart"),65535)),m.responseStart&&0!==m.responseStart&&(f+=Q("t_as",R(m,"responseStart"),65535)),m.responseEnd&&0!==m.responseEnd&&(f+=Q("t_ae",R(m,"responseEnd"),65535)),m.domLoading&&0!==m.domLoading&&(f+=Q("t_dl",R(m,"domLoading"),65535)),m.domInteractive&&0!==m.domInteractive&&(f+=Q("t_di",R(m,"domInteractive"),16777215)),m.domContentLoadedEventStart&&
0!==m.domContentLoadedEventStart&&(f+=Q("t_ls",R(m,"domContentLoadedEventStart"),16777215)),m.domContentLoadedEventEnd&&0!==m.domContentLoadedEventEnd&&(f+=Q("t_le",R(m,"domContentLoadedEventEnd"),16777215)),m.domComplete&&0!==m.domComplete&&(f+=Q("t_dc",R(m,"domComplete"),16777215)),m.loadEventEnd&&0!==m.loadEventEnd&&(f+=Q("t_ee",R(m,"loadEventEnd"),16777215)),b+=f,Gc=!0);nb&&(b+="&pv_id="+nb);D.lastEcommerceOrderTs=x(k)&&String(k).length?k:D.lastEcommerceOrderTs;K(D);M.setCookie(M.getCookieName("ses"),
"*",{msToExpire:Fa});Qb.length&&(b+="&"+Qb);return b}function xa(b){if(!Ma(b))return G("Invalid ecommerce product: "+JSON.stringify(b)),!1;if(!Object.prototype.hasOwnProperty.call(b,"sku"))return G("Missing required SKU property in ecommerce product: "+JSON.stringify(b)+"."),!1;var d=O(b.sku);return"string"!==d&&"number"!==d?(G("Product.sku has to be of type string or number. Received: ".concat(d,". In product: ").concat(JSON.stringify(b))),!1):Object.prototype.hasOwnProperty.call(b,"customDimensions")&&
!Ma(b.customDimensions)?(G('Invalid "customDimensions" property. Expected Object type, but got: '+JSON.stringify(b)+"."),!1):!0}function Z(b,d,f,k){var l=new Date,z=[];var y=""+ka("");y+="&e_t="+b;null!==k&&void 0!==k&&k.currencyCode&&(y+="&cur="+k.currencyCode);if(f){b=f.orderId;k=f.grandTotal;var D=f.subTotal;var N=f.tax;var ha=f.shipping;f=f.discount;if(b){y+="&ec_id="+E(b);var Sa=wb(l)}y+="&revenue="+k;pa(D)&&(y+="&ec_st="+D);pa(N)&&(y+="&ec_tx="+N);pa(ha)&&(y+="&ec_sh="+ha);pa(f)&&(y+="&ec_dt="+
f)}for(l=0;l<d.length;l+=1){x(d[l].name)||(d[l].name="");if(!x(d[l].category))d[l].category="";else if(d[l].category instanceof Array)for(f=0;f<d[l].category.length;f+=1)P(d[l].category[f])||(d[l].category[f]="");x(d[l].price)&&0!==String(d[l].price).length||(d[l].price=0);x(d[l].quantity)&&0!==String(d[l].quantity).length||(d[l].quantity=1);x(d[l].brand)&&0!==String(d[l].brand).length||(d[l].brand="");x(d[l].variant)&&0!==String(d[l].variant).length||(d[l].variant="");x(d[l].customDimensions)||(d[l].customDimensions=
{});f=z;b=f.push;a:for(k=[String(d[l].sku),String(d[l].name),d[l].category,d[l].price,d[l].quantity,d[l].brand,String(d[l].variant),d[l].customDimensions].slice();0<k.length;){D=k[k.length-1];if(!(N=""===D)&&(N=Ma(D)))b:{N=void 0;for(N in D)if(Object.hasOwnProperty.call(D,N)){N=!1;break b}N=!0}if(N)k.pop();else break a}b.call(f,k)}y+="&ec_products="+E(JSON.stringify(z));y=H(y,oa,"ecommerce",Sa);q(y,L)}function ca(b){var d,f=!0;if(b instanceof Array){for(d=0;d<b.length;d+=1)f=f&&xa(b[d]);return f}G("Invalid ecommerce products. Expected value: array of objects. Recieved: "+
JSON.stringify(b)+".");return!1}function zb(b,d){var f;if("object"!==O(b)||null===b)return G("Invalid paymentInformation. Expected object. Recieved: "+JSON.stringify(b)+"."),!1;for(f=0;f<d.length;f+=1){var k=d[f];var l=b[k];if("orderId"===k){if(!x(l)||""===String(l))return G('Invalid paymentInformation. Expected object containing "'+k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!pa(l))return G('Invalid paymentInformation. Expected object containing [number] "'+k+'" attribute. Recieved: '+
JSON.stringify(b)+"."),!1}return!0}function Hc(b,d,f){ya(f,"ecommerceCartUpdate")||(f=void 0);pa(d)?ca(b)&&Z("cart-update",b,{grandTotal:d},f):G('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(d)+".")}function Ic(b,d,f){ya(f,"ecommerceOrder")||(f=void 0);ca(b)&&zb(d,["orderId","grandTotal"])&&Z("order",b,d,f)}function Jc(){var b,d=[];for(b in X)if(Object.prototype.hasOwnProperty.call(X,b)){var f={sku:X[b][0],name:X[b][1],category:X[b][2],price:X[b][3],quantity:X[b][4]};
d.push(f)}return d}function ka(b){b=(b=b||ob)&&b.text?b.text:b;if(!P(b)){var d=document.getElementsByTagName("title");x(d[0])&&(b=d[0].text)}return"action_name="+E(b||"")}function ud(b,d,f){var k="",l;for(l=0;6>l;l++)k+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*Math.random()));nb=k;b=H(ka(b),d,"log");q(b,L,f)}function pb(b,d,f,k){if(b=B.buildInteractionRequestParams(b,d,f,k))return H("".concat(b,"&").concat(ka()),null,"contentInteraction")}function Rb(b,
d){if(!b||!d)return!1;for(var f=B.findTargetNodes(b),k,l=0;l<f.length;l++)if(k=f[l],uc(k,d)&&B.shouldIgnoreInteraction(k))return!1;f=B.findTargetNodesNoDefault(b);if(!f||0===f.length)return!0;for(l=0;l<f.length;l++)if(k=f[l],uc(k,d))return!0;return!1}function Kc(b,d,f){if(b){var k=B.findParentContentNode(b);if(k&&Rb(k,b)&&(b=B.buildContentBlock(k)))return!b.target&&f&&(b.target=f),B.buildInteractionRequestParams(d,b.name,b.piece,b.target)}}function Lc(b){if(0===ua.length)return!1;var d;for(d=0;d<
ua.length;d++){var f=ua[d];if(f.name===b.name&&f.piece===b.piece&&f.target===b.target)return!0}return!1}function Mc(b){return function(d){if(b){var f=B.findParentContentNode(b);if(Rb(f,d.target||d.srcElement||b)){"beacon"!==gb&&p(L);u.isLinkElement(b)&&u.hasNodeAttributeWithValue(b,"href")&&u.hasNodeAttributeWithValue(b,B.CONTENT_TARGET_ATTR)&&(d=u.getAttributeValueFromNode(b,"href"),ab(d||"",aa)||u.setAnyAttribute(b,B.CONTENT_TARGET_ATTR,""));d=mc(b,B,{configTrackerUrl:aa,configDownloadClasses:Sb,
configLinkClasses:Tb,configDownloadExtensions:la,configHostsAlias:ma});if(Ga&&null!==d&&void 0!==d&&d.type)return d.type;var k=B.buildContentBlock(f);if(k&&(f=k.name,d=k.piece,k=u.getAttributeValueFromNode(b,B.CONTENT_TARGET_ATTR)||k.target,f=pb("click",f,d,k)))return q("".concat(f,"&").concat(ka()),L),f}}}}function Nc(b){if(null!==b&&void 0!==b&&b.length){var d,f,k;for(d=0;d<b.length;d++){var l=B.findTargetNodes(b[d]);for(k=0;k<l.length;k++)(f=l[k])&&!f.contentInteractionTrackingSetupDone&&(f.contentInteractionTrackingSetupDone=
!0,W(f,"click",Mc(f)))}}}function Oc(b,d){if(null===b||void 0===b||!b.length)return[];var f,k;for(f=0;f<b.length;f++)Lc(b[f])?(b.splice(f,1),f--):ua.push(b[f]);if(!b.length)return[];Nc(d);var l=[];for(f=0;f<b.length;f++)(k=H("".concat(B.buildImpressionRequestParams(b[f].name,b[f].piece,b[f].target),"&").concat(ka()),void 0,"contentImpressions"))&&l.push(k);return l}function Wa(b){var d=B.collectContent(b);return Oc(d,b)}function Ub(b){if(null===b||void 0===b||!b.length)return[];var d;for(d=0;d<b.length;d++)B.isNodeVisible(b[d])||
(b.splice(d,1),d--);return b.length?Wa(b):[]}function Pc(b,d,f){b=B.buildImpressionRequestParams(b,d,f);return H("".concat(b,"&").concat(ka()),null,"contentImpression")}function Qc(b,d){if(b){var f=B.findParentContentNode(b);if(f=B.buildContentBlock(f))return d||(d="Unknown"),pb(d,f.name,f.piece,f.target)}}function Rc(b,d,f,k,l,z){if(0===da(b).length||0===da(d).length)return G("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),!1;var y=H;
b="e_c="+E(b)+"&e_a="+E(d)+(x(f)?"&e_n="+E(f):"")+(x(k)?"&e_v="+E(k):"");l=y(b+"&"+ka(""),l,"event");q(l,L,z)}function Sc(b,d,f,k,l){d="".concat(ka(),"&").concat(d,"=").concat(E(bb(b,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"})));(b=Kc(l,"click",b))&&(d+="&"+b);f=H(d,f,"link");q(f,L,k,!0,"beacon")}function V(b){!Tc&&"prerendering"in C?C.prerendering?C.addEventListener("prerenderingchange",function f(){C.removeEventListener("prerenderingchange",f);b()}):b():b()}function Vb(b){if(Da){var d=vb(b);
if(jd(d,ma)){sc(d,F().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:aa,browserFeatures:ia,crossDomainTrackingLinkDecorator:Wb});return}}d=mc(b,B,{configTrackerUrl:aa,configDownloadClasses:Sb,configLinkClasses:Tb,configDownloadExtensions:la,configHostsAlias:ma});if(null!==d&&void 0!==d&&d.type)Sc(d.href,d.type,void 0,null,b);else if(Da){b=vb(b);d=B;var f=ma,k=Qa,l=u.getAttributeValueFromNode(b,"href");if(!l||0!==l.indexOf("//")&&0!==l.indexOf("http://")&&0!==l.indexOf("https://"))d=!1;
else{var z=gc(l),y=z.pathname||$a(l,d);l=(z.hostname||La(l)).toLowerCase();d=lc(l,y,f,d)&&!tb(k,Na(l))?!0:!1}d&&sc(b,F().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:aa,browserFeatures:ia,crossDomainTrackingLinkDecorator:Wb})}}function Xa(b){return function(d){d=d||A.event;a:{var f=d;var k=f.which,l=O(f.button);k||"undefined"===l||(C.all&&!C.addEventListener?f.button&1?k=1:f.button&2?k=3:f.button&4&&(k=2):0===f.button||"0"===f.button?k=1:f.button&1?k=2:f.button&2&&(k=3));switch(k){case 1:f=
"left";break a;case 2:f="middle";break a;case 3:f="right";break a}f=void 0}k=d.target||d.srcElement;"click"===d.type?(d=!1,b&&"middle"===f&&(d=!0),k&&!d&&Vb(k)):"mousedown"===d.type?"middle"===f&&k?(qb=f,rb=k):qb=rb=null:"mouseup"===d.type?(f===qb&&k===rb&&Vb(k),qb=rb=null):"contextmenu"===d.type&&Vb(k)}}function vd(b){function d(k){if(k.target){var l=k.target;if(l.closest)l=l.closest("a");else for(;l&&"A"!==l.tagName;)l=l.parentNode;Xb&&l&&!xb(Uc,"ignore").test(l.className)&&Xa(b)(k)}}function f(){cb(document.body,
"click",d,!1);b&&(cb(document.body,"mouseup",d,!1),cb(document.body,"mousedown",d,!1),cb(document.body,"contextmenu",d,!1))}Ga||(W(document.body,"click",d,!1),b&&(W(document.body,"mouseup",d,!1),W(document.body,"mousedown",d,!1),W(document.body,"contextmenu",d,!1)),Ga=f)}function Vc(b,d,f){function k(){l=!0}if(Ha)return!0;Ha=!0;var l=!1,z,y;Aa(function(){function D(m){setTimeout(function(){Ha&&(l=!1,f.trackVisibleContentImpressions(),D(m))},m)}function N(m){setTimeout(function(){Ha&&(l&&(l=!1,f.trackVisibleContentImpressions()),
N(m))},m)}function ha(m){if(!m)return!1;var Ya=m.getBoundingClientRect();if(0>=Ya.width||0>=Ya.height)return!1;if(A.getComputedStyle){var ba;var Ia=null===(ba=C.defaultView)||void 0===ba?void 0:ba.getComputedStyle(m,null)}else m.currentStyle&&(Ia=m.currentStyle);Ia||(Ia={});return"0"===Ia.opacity||"none"===Ia.display||"hidden"===Ia.visibility?!1:m.parentNode instanceof Element?ha(m.parentNode):!0}function Sa(m){var Ya=[],ba;for(ba=0;ba<m.length;ba+=1)m[ba].isIntersecting&&ha(m[ba].target)&&B.isOrWasNodeInViewport(m[ba].target)&&
Ya.push(m[ba].target);m=Wa(Ya);v(m,L)}function ta(){if(A.IntersectionObserver){Ja||(Ja=new A.IntersectionObserver(Sa,{threshold:0}));var m=B.findContentNodes();for(y=0;y<m.length;y+=1)m[y].getAttribute(B.CONTENT_WATCHED_ATTR)||(Ja.observe(m[y]),m[y].setAttribute(B.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||d&&0<d)&&ta();if(b){z=["scroll","resize"];for(y=0;y<z.length;y++)C.addEventListener?C.addEventListener(z[y],k):A.attachEvent("on"+z[y],k);N(100)}d&&0<d&&(d=parseInt(d,10),D(d))})}function Wc(b,
d,f,k){if(Yb){var l=String(b).substring(0,16E3);V(function(){var z=d+":"+f;x(k)&&(z+=":"+k);var y=JSON.stringify({category:"JavaScript Errors",action:z,message:l});Xc&&-1!==Y(Zb,y)||(Zb.push(y),Rc("JavaScript Errors",z,l))})}}var $b=id(C.domain,A.location.href,td()),Qa=Na($b[0]),jb=$b[1],Kb=$b[2],Yb=!1,gb="beacon",Cc=!0,Dc=!1,Hb=!1,Gb="application/x-www-form-urlencoded; charset=UTF-8",aa=a||"",ac="",Qb="",Ea=c||"",kb=!1,Ec=!1,Db=null,Eb=null,Ua="",Ca="",bc=10,Ra,ob="",la="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
ma=[Qa],Uc=[],Sb=[],Tb=[],L=500,Fb=null,Yc=!1,Ta=!1,oa,Zc="_pk_",Ac=180,hb,ib,$c=!1,sa=!1,ad=!0,fb=!1,Tc=!1,Ib=339552E5,Fa=18E5,Ob=!0,Pb=0,Fc=!1,S,ja={},Va={},Pa,ea={},na={},cc=200,X={},ia={},ua=[],Ha=!1,Ja,Ba,Ga=!1,Xb=!1,Da=!1,Wb=tc,Bc=ub,vc=null,qb,rb,zc=pc,yc,nb,mb=0,Xc=!1,Zb=[],Jb=["id","ses","cvar"],Lb="jstc",Nb="2.29.0",lb="",Mb="",wc=ld({onResolve:function(){for(var b=0;b<eb.length;b++){var d=eb[b];if("single"===d.type)q(d.request,d.delay,d.callback,d.force,d.method);else if("bulk"===d.type)v(d.requests,
d.delay);else throw Error("[processQueue] unprocessable request type: ".concat(JSON.stringify(d)));}}});try{ob=C.title}catch(b){ob=""}var Ka=nd({onPing:e}),M=pd({decodeWrapper:wd,encodeWrapper:E,getCookiesConfig:function(){return{cookiesDisabled:sa,domain:hb,path:ib,isSecure:$c,trackerSiteId:Ea,cookieNamePrefix:Zc,domainHash:yc}},documentAlias:C,navigatorAlias:ra}),eb=[];this.setCustomVariableMaximumLength=function(b){cc=b};ia=qd(function(){return M.hasCookies()});w();this.getQuery=function(){return u};
this.getContent=function(){return B};this.buildContentImpressionRequest=Pc;this.buildContentInteractionRequest=pb;this.buildContentInteractionRequestNode=Qc;this.getContentImpressionsRequestsFromNodes=Wa;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=Ub;this.trackCallbackOnLoad=Aa;this.trackCallbackOnReady=Oa;this.buildContentImpressionsRequests=Oc;this.wasContentImpressionAlreadyTracked=Lc;this.appendContentInteractionToRequestIfPossible=Kc;this.setupInteractionsTracking=Nc;this.trackContentImpressionClickInteraction=
Mc;this.internalIsNodeVisible=yb;this.isNodeAuthorizedToTriggerInteraction=Rb;this.getDomains=function(){return ma};this.getConfigIdPageView=function(){return nb};this.getConfigDownloadExtensions=function(){return la};this.enableTrackOnlyVisibleContent=function(b,d){return Vc(b,d,this)};this.clearTrackedContentImpressions=function(){ua=[]};this.getTrackedContentImpressions=function(){return ua};this.clearEnableTrackOnlyVisibleContent=function(){var b;Ha=!1;null===(b=Ja)||void 0===b||b.disconnect();
Ja=void 0};this.disableLinkTracking=function(){"function"===typeof Ga&&Ga();Xb=Ga=!1};this.getConfigVisitorCookieTimeout=function(){return Ib};this.removeAllAsyncTrackersButFirst=function(){U=[U[0]]};this.ping=function(){var b=H("ping=6",null,"ping");q(b,L)};this.getVisitorId=function(){return F().uuid};this.getVisitorInfo=function(){return t()};this.setTrackerUrl=function(b){aa=b};this.getTrackerUrl=function(){return aa};this.getPiwikUrl=function(){var b=this.getTrackerUrl();if(ac)b=ac;else{b=B.toAbsoluteUrl(b);
if(-1!==b.indexOf("?")){var d=b.indexOf("?");b=b.slice(0,d)}wa(b,"ppms.php")?b=b.substr(0,b.length-8):wa(b,".php")&&(d=b.lastIndexOf("/"),b=b.slice(0,d+1));wa(b,"/js/")&&(b=b.substr(0,b.length-3))}return b};this.addTracker=function(b,d){if(!d)throw Error("A siteId must be given to add a new tracker");x(b)&&null!==b||(b=this.getTrackerUrl());var f=new Cb(b,d);U.push(f);return f};this.getSiteId=function(){return Ea};this.setSiteId=function(b){Ea=b;K();if(ad){var d=this.getTrackerUrl(),f=C.createElement("script");
f.setAttribute("id","ppas_container_configuration");f.setAttribute("data-appid",b);b=f.setAttribute;var k=C.createElement("a");k.href=d;b.call(f,"data-host",k.host);C.getElementsByTagName("head")[0].appendChild(f)}};this.setVisitorIdCookie=function(){K()};this.resetUserId=function(){Ua=""};this.setUserIsAnonymous=function(b){kb=b};this.setSessionIdStrictPrivacyMode=function(b){Ec=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);
bc=b};this.getTimingDataSamplingOnPageLoad=function(){return bc};this.setUserId=function(b){x(b)&&b.length&&(Ua=b)};this.getUserId=function(){return Ua};this.setCustomData=function(b,d){Ma(b)?oa=b:(oa||(oa={}),oa[b]=d)};this.getCustomData=function(){return oa};this.setCustomRequestProcessing=function(b){Pa=b};this.appendToTrackingUrl=function(b){Qb=b};this.getRequest=function(b){return H(b)};this.setCustomDimension=function(b,d){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(na,b)?fd("Custom dimension "+
b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):(x(d)||(d=""),P(d)||(d=String(d)),ea[b]=d))};this.getCustomDimension=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(ea,b))return ea[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete ea[b],delete na[b])};this.setCustomDimensionValue=function(b,d){b=parseInt(b,10);0<b&&(x(d)||(d=""),P(d)||(d=String(d)),na[b]=d,delete ea[b])};this.getCustomDimensionValue=
function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(na,b))return na[b]};this.setCustomVariable=function(b,d,f,k){x(k)||(k="visit");x(d)&&(x(f)||(f=""),0<b&&(d=P(d)?d:String(d),f=P(f)?f:String(f),d=[d.slice(0,cc),f.slice(0,cc)],"visit"===k||2===k?(S||(S=r()),S[b]=d):"page"===k||3===k?ja[b]=d:"event"===k&&(Va[b]=d)))};this.getCustomVariable=function(b,d){x(d)||(d="visit");if("page"===d||3===d)var f=ja[b];else if("event"===d)f=Va[b];else if("visit"===d||2===d)S||(S=r()),f=S[b];
return x(f)&&""!==f[0]?f:!1};this.deleteCustomVariable=function(b,d){this.getCustomVariable(b,d)&&this.setCustomVariable(b,"","",d)};this.deleteCustomVariables=function(b){if("page"===b||3===b)ja={};else if("event"===b)Va={};else if("visit"===b||2===b)S={}};this.storeCustomVariablesInCookie=function(){Fc=!0};this.setLinkTrackingTimer=function(b){L=b};this.getLinkTrackingTimer=function(){return L};this.setDownloadExtensions=function(b){P(b)&&(b=b.split("|"));la=b};this.addDownloadExtensions=function(b){var d;
P(b)&&(b=b.split("|"));for(d=0;d<b.length;d++)la.push(b[d])};this.removeDownloadExtensions=function(b){var d,f=[];P(b)&&(b=b.split("|"));for(d=0;d<la.length;d++)-1===Y(b,la[d])&&f.push(la[d]);la=f};this.setDomains=function(b){ma=P(b)?[b]:b;b=!1;for(var d=0;d<ma.length;d++){var f=String(ma[d]);if(tb(Qa,Na(f))){b=!0;break}if((f=$a(f,B))&&"/"!==f&&"/*"!==f){b=!0;break}}b||ma.push(Qa)};this.enableCrossDomainLinking=function(){Da=!0};this.disableCrossDomainLinking=function(){Da=!1};this.isCrossDomainLinkingEnabled=
function(){return Da};this.customCrossDomainLinkDecorator=function(b){Wb=b};this.customCrossDomainLinkVisitorIdGetter=function(b){Bc=b};this.setCrossDomainLinkingTimeout=function(b){Ac=b};this.getCrossDomainLinkingUrlParameter=function(){var b=F().uuid;return E("pk_vid")+"="+E(b+rc(ia))};this.setIgnoreClasses=function(b){Uc=P(b)?[b]:b};this.setRequestMethod=function(b){gb=b||"beacon"};this.setRequestContentType=function(b){Gb=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=
function(b){Kb=b};this.setCustomUrl=function(b){if("string"!==typeof b)G("[setCustomUrl]: url must be a string, got: ".concat(JSON.stringify(b)));else{var d=jb,f=Ta;ic(b)?Ra=b:"/"===b.slice(0,1)?Ra=(ic(d)||"")+"://"+La(d)+b:(d=bb(d,{discardHashTag:f,visitorIdUrlParameter:"pk_vid"}),f=d.indexOf("?"),0<=f&&(d=d.slice(0,f)),f=d.lastIndexOf("/"),f!==d.length-1&&(d=d.slice(0,f+1)),Ra=d+b)}};this.getCurrentUrl=function(){return Ra||jb};this.setDocumentTitle=function(b){ob=b};this.setAPIUrl=function(b){ac=
b};this.setDownloadClasses=function(b){Sb=P(b)?[b]:b};this.setLinkClasses=function(b){Tb=P(b)?[b]:b};this.discardHashTag=function(b){Ta=b};this.setCookieNamePrefix=function(b){Zc=b;S=r()};this.setCookieDomain=function(b){hb=Na(b);w()};this.getCookieDomain=function(){return hb};this.hasCookies=function(){return"1"===M.hasCookies()};this.setSessionCookie=function(b,d,f){if(!b)throw Error("Missing cookie name");x(f)||(f=Fa);Jb.push(b);M.setCookie(M.getCookieName(b),d,{msToExpire:f})};this.getCookie=
function(b){b=M.getCookie(M.getCookieName(b));return 0===b?null:b};this.setCookiePath=function(b){ib=b;w()};this.getCookiePath=function(){return ib};this.setVisitorCookieTimeout=function(b){Ib=1E3*b};this.setSessionCookieTimeout=function(b){Fa=1E3*b};this.getSessionCookieTimeout=function(){return Fa};this.setReferralCookieTimeout=function(){};this.setSecureCookie=function(b){$c=b};this.disableCookies=function(){sa=!0;Ea&&J()};this.enableCookies=function(){sa=!1};this.deleteCookies=function(){J()};
this.setSiteInspectorSetup=function(b){ad=b};this.setDoNotTrack=function(b){var d=ra.doNotTrack||ra.msDoNotTrack;(fb=b&&("yes"===d||"1"===d))&&this.disableCookies()};this.addListener=function(b,d){var f=d;"undefined"===O(f)&&(f=!0);W(b,"click",Xa(!!f),!1);f&&(W(b,"mouseup",Xa(f),!1),W(b,"mousedown",Xa(f),!1),W(b,"contextmenu",Xa(f),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);Xb=!0;V(function(){Oa(function(){vd(b)})})};this.enableJSErrorTracking=
function(b){x(b)||(b=!0);if(!Yb){Yb=!0;Xc=b;var d=A.onerror;A.onerror=function(f,k,l,z,y){Wc(f,k,l,z);return d?d(f,k,l,z,y):!1}}};this.disablePerformanceTracking=function(){Ob=!1};this.setGenerationTimeMs=function(b){Pb=parseInt(b,10)};this.enableHeartBeatTimer=function(b){if(b){var d=nc(b);if(!d.isValid){G(d.error);return}}else b=oc;Ka.setTimings(b);Yc=!0;null!==vc&&Ka.enable()};this.disableHeartBeatTimer=function(){Ka.disable()};this.killFrame=function(){A.location!==A.top.location&&(A.top.location=
A.location)};this.redirectFile=function(b){"file:"===A.location.protocol&&(A.location=b)};this.setCountPreRendered=function(b){Tc=b};this.trackGoal=function(b,d,f,k){ya(k,"trackGoal")||(k=void 0);V(function(){var l=k;l=H("idgoal="+b+(d?"&revenue="+d:"")+"&"+ka("")+(null!==l&&void 0!==l&&l.currencyCode?"&cur="+l.currencyCode:""),f,"goal");q(l,L)})};this.trackLink=function(b,d,f,k){V(function(){Sc(b,d,f,k)})};this.getNumTrackedPageViews=function(){return mb};this.trackHeartBeat=function(b){var d=!C.hasFocus||
C.hasFocus();Ka.isEnabled()&&d&&(!1===Db||!0===Eb)&&(d=qa.PeriodicHeartbeat,null!==b&&void 0!==b&&b.lastHeartbeat&&(d=qa.LastHeartbeat),null!==b&&void 0!==b&&b.blurHeartbeat&&(d=qa.BlurHeartbeat),e(d))};this.trackPageView=function(b,d,f){ua=[];Zb=[];V(function(){mb++;ud(b,d,f);Yc&&!Ka.isEnabled()&&Ka.enable();1>=mb&&bc>=Math.floor(100*Math.random()+1)&&Aa(function(){setTimeout(function(){var k=H("ping=5",null,"ping");q(k,L)},0)})})};this.trackAllContentImpressions=function(){V(function(){Oa(function(){var b=
B.findContentNodes();b=Wa(b);v(b,L)})})};this.trackVisibleContentImpressions=function(b,d){x(b)||(b=!0);x(d)||(d=750);Vc(b,d,this);Ja||V(function(){Aa(function(){var f=B.findContentNodes();f=Ub(f);v(f,L)})})};this.trackContentImpression=function(b,d,f){b=da(b);d=da(d||"Unknown");f=da(f||"");b&&V(function(){var k=Pc(b,d,f);q(k,L)})};this.trackContentImpressionsWithinNode=function(b){b&&V(function(){Ha?Aa(function(){var d=B.findContentNodesWithinNode(b);d=Ub(d);v(d,L)}):Oa(function(){var d=B.findContentNodesWithinNode(b);
d=Wa(d);v(d,L)})})};this.trackContentInteraction=function(b,d,f,k){b=da(b);d=da(d);f=da(f||"Unknown");k=da(k||"");b&&d&&V(function(){var l=pb(b,d,f,k);l&&q(l,L)})};this.trackContentInteractionNode=function(b,d){b&&V(function(){var f=Qc(b,d);f&&q(f,L)})};this.logAllContentBlocksOnPage=function(){var b=B.findContentNodes();b=B.collectContent(b);console.log(b)};this.trackEvent=function(b,d,f,k,l,z){x(k)&&!pa(k)&&G("[trackEvent]: Value parameter must be a number or number representation. Received: ".concat(JSON.stringify(k)));
V(function(){Rc(String(b),String(d),f,k,l,z)})};this.trackSiteSearch=function(b,d,f,k){V(function(){var l=H("search="+E(b)+(d?"&search_cats="+E(JSON.stringify(P(d)?[d]:d)):"")+(x(f)?"&search_count="+f:""),k,"sitesearch");q(l,L)})};this.setEcommerceView=function(b,d,f,k){x(f)&&f.length?f instanceof Array&&(f=JSON.stringify(f)):f="";ja[5]=["_pkc",f];x(k)&&String(k).length&&(ja[2]=["_pkp",k]);if(x(b)&&b.length||x(d)&&d.length)x(b)&&b.length&&(ja[3]=["_pks",b]),x(d)&&d.length||(d=""),ja[4]=["_pkn",d]};
this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(X))};this.addEcommerceItem=function(b,d,f,k,l){b.length&&(X[b]=[b,d,f,k,l])};this.removeEcommerceItem=function(b){b.length&&delete X[b]};this.clearEcommerceCart=function(){X={}};this.trackEcommerceOrder=function(b,d,f,k,l,z){String(b).length&&x(d)&&(Ic(Jc(),{orderId:b,grandTotal:d,subTotal:f,tax:k,shipping:l,discount:z}),X={})};this.trackEcommerceCartUpdate=function(b){Hc(Jc(),b)};this.ecommerceProductDetailView=function(b,d){ya(d,
"ecommerceProductDetailView")||(d=void 0);ca(b)&&Z("product-detail-view",b,void 0,d)};this.ecommerceAddToCart=function(b,d){ya(d,"ecommerceAddToCart")||(d=void 0);ca(b)&&Z("add-to-cart",b,void 0,d)};this.ecommerceRemoveFromCart=function(b,d){ya(d,"ecommerceRemoveFromCart")||(d=void 0);ca(b)&&Z("remove-from-cart",b,void 0,d)};this.ecommerceCartUpdate=Hc;this.ecommerceOrder=Ic;this.trackError=function(b){if(b)try{var d=xd.parse(b)[0];Wc(b.message,d.fileName||"",d.lineNumber||0,d.columnNumber||0)}catch(f){}};
this.trackRequest=function(b,d,f,k){V(function(){var l=H(b,d,k);q(l,L,f)})};this.deanonymizeUser=function(){this.setUserIsAnonymous(!1);var b=H("ping=4",null,"ping");q(b,L)};this.getTrackingSource=function(){return[Lb,Nb]};this.setTrackingSource=function(b,d){Lb=String(b);void 0!==d&&(Nb=String(d))};this.setTrackingSourceProvider=function(b,d){"string"!==typeof b?G("[setTrackingSourceProvider]: 'provider' has to be of type string"):"string"!==typeof d?G("[setTrackingSourceProvider]: 'providerVersion' has to be of type string"):
(lb=b,Mb=d)};this.getTrackingSourceProvider=function(){if(lb)return[lb,Mb]};this.setIpTracking=function(b){Cc=b};this.setDeviceDataAnonymization=function(b){"boolean"!==typeof b?G("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):Dc=b};this.setEnableClientHints=function(b){"boolean"!==typeof b?G("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Hb=b};dc.trigger("TrackerSetup",[this])}function yd(a,c){for(var e={},g=0;g<c.length;g++){var h=
c[g];e[h]=1;for(var p=0;p<a.length;p++){var n;if(null!==(n=a[p])&&void 0!==n&&n[0]){var q=a[p][0];h===q&&(za(a[p]),delete a[p],1<e[q]&&"addTracker"!==q&&"enableLinkTracking"!==q&&"setSecureCookie"!==q&&"enableCrossDomainLinking"!==q&&G("The method "+q+' is registered more than once in "'+I.queueName+'" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),e[q]++)}}}za(["setVisitorIdCookie"])}function bd(a,c){var e=new Cb(a,c);U.push(e);var g=
window[I.queueName].splice(0,window[I.queueName].length),h=sd(g,cd,zd),p=h.toApplySecond;g=h.toApplyLast;yd(h.toApplyFirst,cd);for(h=0;h<p.length;h++)za(p[h]);p=window[I.queueName];for(h=0;h<p.length;h++)za(p[h]);for(p=0;p<g.length;p++)za(g[p]);if("number"===typeof window[I.queueName].length){var n={push:za},q=Date.now();window[I.queueName]=n;var v=setInterval(function(){6E4<Date.now()-q?clearInterval(v):window[I.queueName]!==n&&(G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),
clearInterval(v))},1E3)}else G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");return e}function Ad(a,c,e,g){function h(n){try{if(window["piwik_"+n])return window["piwik_"+n]}catch(q){}}var p=window.Piwik.getTracker(e,c);p.setDocumentTitle(a);p.setCustomData(g);(a=h("tracker_pause"))&&
p.setLinkTrackingTimer(a);(a=h("download_extensions"))&&p.setDownloadExtensions(a);(a=h("hosts_alias"))&&p.setDomains(a);(a=h("ignore_classes"))&&p.setIgnoreClasses(a);p.setTimingDataSamplingOnPageLoad(0);p.trackPageView();h("install_tracker")&&(window.piwik_track=function(n,q,v,w){p.setSiteId(q);p.setTrackerUrl(v);p.trackLink(n,w)},p.enableLinkTracking())}var I={queueName:"_paq",objectName:"Piwik"},sb={exports:{}},Za={exports:{}},hd=Za.exports,fc,Bd=sb.exports,dd,xd=function(a){return a&&a.__esModule&&
Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a}(function(){if(dd)return sb.exports;dd=1;(function(a,c){(function(e,g){a.exports=g(gd())})(Bd,function(e){var g=/(^|@)\S+:\d+/,h=/^\s*at .*(\S+:\d+|\(native\))/m,p=/^(eval@)?(\[native code])?$/;return{parse:function(n){if("undefined"!==typeof n.stacktrace||"undefined"!==typeof n["opera#sourceloc"])return this.parseOpera(n);if(n.stack&&n.stack.match(h))return this.parseV8OrIE(n);if(n.stack)return this.parseFFOrSafari(n);throw Error("Cannot parse given Error object");
},extractLocation:function(n){if(-1===n.indexOf(":"))return[n];n=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(n.replace(/[()]/g,""));return[n[1],n[2]||void 0,n[3]||void 0]},parseV8OrIE:function(n){return n.stack.split("\n").filter(function(q){return!!q.match(h)},this).map(function(q){-1<q.indexOf("(eval ")&&(q=q.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,""));var v=q.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),w=v.match(/ (\(.+\)$)/);v=w?v.replace(w[0],""):v;
var r=this.extractLocation(w?w[1]:v);v=w&&v||void 0;w=-1<["eval","<anonymous>"].indexOf(r[0])?void 0:r[0];return new e({functionName:v,fileName:w,lineNumber:r[1],columnNumber:r[2],source:q})},this)},parseFFOrSafari:function(n){return n.stack.split("\n").filter(function(q){return!q.match(p)},this).map(function(q){-1<q.indexOf(" > eval")&&(q=q.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,":$1"));if(-1===q.indexOf("@")&&-1===q.indexOf(":"))return new e({functionName:q});var v=/((.*".+"[^@]*)?[^@]*)(?:@)/,
w=q.match(v);w=w&&w[1]?w[1]:void 0;v=this.extractLocation(q.replace(v,""));return new e({functionName:w,fileName:v[0],lineNumber:v[1],columnNumber:v[2],source:q})},this)},parseOpera:function(n){return!n.stacktrace||-1<n.message.indexOf("\n")&&n.message.split("\n").length>n.stacktrace.split("\n").length?this.parseOpera9(n):n.stack?this.parseOpera11(n):this.parseOpera10(n)},parseOpera9:function(n){var q=/Line (\d+).*script (?:in )?(\S+)/i;n=n.message.split("\n");for(var v=[],w=2,r=n.length;w<r;w+=2){var t=
q.exec(n[w]);t&&v.push(new e({fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera10:function(n){var q=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;n=n.stacktrace.split("\n");for(var v=[],w=0,r=n.length;w<r;w+=2){var t=q.exec(n[w]);t&&v.push(new e({functionName:t[3]||void 0,fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera11:function(n){return n.stack.split("\n").filter(function(q){return!!q.match(g)&&!q.match(/^Error created at/)},this).map(function(q){var v=
q.split("@"),w=this.extractLocation(v.pop()),r=v.shift()||"";v=r.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var t;r.match(/\(([^)]*)\)/)&&(t=r.replace(/^[^(]+\(([^)]*)\)$/,"$1"));t=void 0===t||"[arguments not available]"===t?void 0:t.split(",");return new e({functionName:v,args:t,fileName:w[0],lineNumber:w[1],columnNumber:w[2],source:q})},this)}}})})(sb);return sb.exports}()),u={htmlCollectionToArray:function(a){var c=[],e;if(!a||!a.length)return c;for(e=0;e<a.length;e++)c.push(a[e]);
return c},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return u.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var c,e=[];for(c=0;c<a.length;c++){var g=u.find(a[c]);e=e.concat(g)}return e=u.makeNodesUnique(e)},findNodesByTagName:function(a,c){if(!a||!c||!a.getElementsByTagName)return[];var e=a.getElementsByTagName(c);return u.htmlCollectionToArray(e)},makeNodesUnique:function(a){var c=[].concat(a);a.sort(function(n,q){if(n===
q)return 0;var v=Y(c,n),w=Y(c,q);return v===w?0:v>w?-1:1});if(1>=a.length)return a;var e=0,g=0,h=[],p;for(p=a[e++];p;)p===a[e]&&(g=h.push(e)),p=a[e++]||null;for(;g--;)a.splice(h[g],1);return a},getAttributeValueFromNode:function(a,c){if(u.hasNodeAttribute(a,c)){if(a&&a.getAttribute)return a.getAttribute(c);if(a&&a.attributes&&"undefined"!==O(a.attributes[c])){if(a.attributes[c].value)return a.attributes[c].value;if(a.attributes[c].nodeValue)return a.attributes[c].nodeValue;var e,g=a.attributes;if(g){for(e=
0;e<g.length;e++)if(g[e].nodeName===c)return g[e].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,c){return!!u.getAttributeValueFromNode(a,c)},hasNodeAttribute:function(a,c){return a&&a.hasAttribute?a.hasAttribute(c):a&&a.attributes?"undefined"!==O(a.attributes[c]):!1},hasNodeCssClass:function(a,c){if(a&&c&&a.className){var e="string"===typeof a.className?a.className.split(" "):[];if(-1!==Y(e,c))return!0}return!1},findNodesHavingAttribute:function(a,c,e){e||(e=[]);if(!a||!c)return e;
a=jc(a);if(!a)return e;var g;for(g=0;g<a.length;g++){var h=a[g];u.hasNodeAttribute(h,c)&&e.push(h);e=u.findNodesHavingAttribute(h,c,e)}return e},findFirstNodeHavingAttribute:function(a,c){if(a&&c){if(u.hasNodeAttribute(a,c))return a;var e=u.findNodesHavingAttribute(a,c);if(e&&e.length)return e[0]}},findFirstNodeHavingAttributeWithValue:function(a,c){if(a&&c){if(u.hasNodeAttributeWithValue(a,c))return a;var e=u.findNodesHavingAttribute(a,c);if(e&&e.length){var g;for(g=0;g<e.length;g++)if(u.getAttributeValueFromNode(e[g],
c))return e[g]}}},findNodesHavingCssClass:function(a,c,e){e||(e=[]);if(!a||!c)return e;if(a.getElementsByClassName)return c=a.getElementsByClassName(c),u.htmlCollectionToArray(c);a=jc(a);if(!a)return[];var g;for(g=0;g<a.length;g++){var h=a[g];u.hasNodeCssClass(h,c)&&e.push(h);e=u.findNodesHavingCssClass(h,c,e)}return e},findFirstNodeHavingClass:function(a,c){if(a&&c){if(u.hasNodeCssClass(a,c))return a;var e=u.findNodesHavingCssClass(a,c);if(e&&e.length)return e[0]}},isLinkElement:function(a){if(!a)return!1;
a=String(a.nodeName).toLowerCase();return-1!==Y(["a","area"],a)},setAnyAttribute:function(a,c,e){a&&c&&(a.setAttribute?a.setAttribute(c,e):a[c]=e)}},kd=/^[a-z]+:\/\/.+$/i,ed={model:"ch_m",brands:"ch_b",platform:"ch_p",platformVersion:"ch_pv",fullVersionList:"ch_fvl"},md=Object.keys(ed),xc=function(a){if("object"!==O(a))return"";var c="",e;for(e in a){var g=ed[e],h=a[e];if(g&&h){g="&".concat(g,"=");var p=g.concat;h?(h="object"===O(h)?JSON.stringify(h):h,h=window.encodeURIComponent(h)):h="";c+=p.call(g,
h)}}return c},oc=[15,30,60,120,240,480,960,1800],qa={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3},Ab=Object.freeze({pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"}),db,fa={},C=document,ra=navigator,A=window,Gc=!1,E=A.encodeURIComponent,wd=A.decodeURIComponent,U=[],ec=[],B=
{CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,findContentNodes:function(){return u.findMultiple(["."+
this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var c=u.findNodesHavingCssClass(a,this.CONTENT_CLASS),e=u.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(e.length){var g;for(g=0;g<e.length;g++)c.push(e[g])}u.hasNodeAttribute(a,this.CONTENT_ATTR)?c.push(a):u.hasNodeCssClass(a,this.CONTENT_CLASS)&&c.push(a);return c=u.makeNodesUnique(c)},findParentContentNode:function(a){if(a)for(var c=0;a&&a!==C&&a.parentNode;){if(u.hasNodeAttribute(a,this.CONTENT_ATTR)||
u.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<c)break;c++}},findPieceNode:function(a){var c;(c=u.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(c=u.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return c?c:a},findTargetNodeNoDefault:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(c||(c=u.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(c=u.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return c}},
findTargetNode:function(a){var c=this.findTargetNodeNoDefault(a);return c?c:a},findTargetNodesNoDefault:function(a){if(a){var c=u.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(0<c.length)return c;c=u.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS);if(0<c.length)return c}},findTargetNodes:function(a){var c=B.findTargetNodesNoDefault(a);return c&&0<c.length?c:[a]},findContentName:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(c)return u.getAttributeValueFromNode(c,
this.CONTENT_NAME_ATTR);if(c=this.findContentPiece(a))return this.removeDomainIfIsInLink(c);if(u.hasNodeAttributeWithValue(a,"title"))return u.getAttributeValueFromNode(a,"title");c=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(c,"title"))return u.getAttributeValueFromNode(c,"title");a=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(a,"title"))return u.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var c=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);
if(c)return u.getAttributeValueFromNode(c,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var c=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(c,this.CONTENT_TARGET_ATTR))return u.getAttributeValueFromNode(c,this.CONTENT_TARGET_ATTR);if(u.hasNodeAttributeWithValue(c,"href"))return a=u.getAttributeValueFromNode(c,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(a,
"href"))return a=u.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){var c;null!==(c=a)&&void 0!==c&&c.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var c=a.nodeName.toLowerCase(),
e=u.findFirstNodeHavingAttributeWithValue(a,"src");if(-1!==Y(["img","embed","video","audio"],c)&&e)return u.getAttributeValueFromNode(e,"src");if("object"===c&&u.hasNodeAttributeWithValue(a,"data"))return u.getAttributeValueFromNode(a,"data");if("object"===c){c=u.findNodesByTagName(a,"param");if(c.length)for(e=0;e<c.length;e++)if("movie"===u.getAttributeValueFromNode(c[e],"name")&&u.hasNodeAttributeWithValue(c[e],"value"))return u.getAttributeValueFromNode(c[e],"value");a=u.findNodesByTagName(a,"embed");
if(a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return da(a)},isOrWasNodeInViewport:function(a){if(null===a||void 0===a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var c=a.getBoundingClientRect(),e=C.documentElement,g=0>c.top;g&&a.offsetTop&&(g=0<a.offsetTop+c.height);a=e.clientWidth;A.innerWidth&&a>A.innerWidth&&(a=A.innerWidth);e=e.clientHeight;A.innerHeight&&e>A.innerHeight&&(e=A.innerHeight);return(0<c.bottom||g)&&0<c.right&&c.left<a&&(c.top<e||g)},isNodeVisible:function(a){var c=
yb(a);a=this.isOrWasNodeInViewport(a);return c&&a},buildInteractionRequestParams:function(a,c,e,g){var h="";a&&(h+="c_i="+E(a));c&&(h&&(h+="&"),h+="c_n="+E(c));e&&(h&&(h+="&"),h+="c_p="+E(e));g&&(h&&(h+="&"),h+="c_t="+E(g));return h},buildImpressionRequestParams:function(a,c,e){a="c_n="+E(a)+"&c_p="+E(c);e&&(a+="&c_t="+E(e));return a},buildContentBlock:function(a){if(a){var c=this.findContentName(a),e=this.findContentPiece(a);a=this.findContentTarget(a);c=c?this.trim(c):"Unknown";e=e?this.trim(e):
"Unknown";a=a?this.trim(a):"";return{name:c,piece:e,target:a}}},collectContent:function(a){if(null===a||void 0===a||!a.length)return[];var c=[],e;for(e=0;e<a.length;e++){var g=this.buildContentBlock(a[e]);x(g)&&c.push(g)}return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||A.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){var c;return a&&String(a)===a||""===a?""===a?this.getLocation().href:
-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+((null===(c=/(.*\/)/.exec(this.getLocation().pathname))||void 0===c?void 0:c[0])||"")+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var c=this.getLocation().origin;return c===a?!0:0===String(a).indexOf(c)?
":"===String(a).substr(c.length,1)?!1:!0:!1},setHrefAttribute:function(a,c){a&&c&&u.setAnyAttribute(a,"href",c)},shouldIgnoreInteraction:function(a){var c=u.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=u.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return c||a}},cd="addTracker setTrackingSourceProvider disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints setUserIsAnonymous".split(" "),
zd=["trackError"];W(A,"beforeunload",function(){for(var a=U,c=db,e=0;e<a.length;e+=1)a[e].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<ec.length;a+=1)ec[a].trackHeartBeat({lastHeartbeat:!0});if(c){do a=new Date;while(a.getTime()<c)}},!1);var dc={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,c,e,g){"undefined"===O(g)&&(g=!1);W(a,c,e,g)},onLoad:Aa,onReady:Oa,isNodeVisible:yb,isOrWasNodeVisible:B.isNodeVisible},on:function(a,c){fa[a]||(fa[a]=[]);fa[a].push(c)},off:function(a,c){if(fa[a]){var e=
0;for(e;e<fa[a].length;e++)fa[a][e]===c&&fa[a].splice(e,1)}},trigger:function(a,c,e){if(fa[a]){var g=0;for(g;g<fa[a].length;g++)fa[a][g].apply(e||A,c)}},getTracker:function(a,c){x(c)||(c=this.getAsyncTracker().getSiteId());x(a)||(a=this.getAsyncTracker().getTrackerUrl());var e=new Cb(a,c);ec.push(e);return e},getAsyncTrackers:function(){return U},addTracker:function(a,c){return U.length?U[0].addTracker(a,c):bd(a,c)},getAsyncTracker:function(a,c){if(U[0])var e=U[0];else return bd(a,c);if(!c&&!a)return e;
x(c)&&null!==c||(c=e.getSiteId());x(a)&&null!==a||(a=e.getTrackerUrl());var g=0;for(g;g<U.length;g++)if(e=U[g],String(e.getSiteId())===String(c)&&e.getTrackerUrl()===a)return e}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return dc});var Cd=dc;"object"!==O(window[I.queueName])&&(window[I.queueName]=[]);"object"!==O(window[I.objectName])&&(window[I.objectName]=Cd);(function(){window[I.objectName].getAsyncTrackers().length?G("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):
("object"!==O(window[I.queueName])||"undefined"===O(window[I.queueName].length)?0:window[I.queueName].length)?window[I.objectName].addTracker():window[I.queueName]={push:function(a){G(I.queueName+".push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.",
a)}};window[I.objectName].trigger("PiwikInitialized",[]);window[I.objectName].initialized=!0})();"undefined"===O(window.AnalyticsTracker)&&(window.AnalyticsTracker=window[I.objectName]);"function"!==typeof window[I.objectName].piwik_log&&(window.piwik_log=Ad)})()
//# sourceMappingURL=ppms.js.map
